---
name: build
on: [ push ]
jobs:
  make-native:
    name: make native
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: make
          working-directory: ${{ env.GITHUB_WORKSPACE }}
          run: make
        - name: run
          run: $GITHUB_WORKSPACE/hello
  make-container:
    name: make container
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: build
          working-directory: ${{ env.GITHUB_WORKSPACE }}
          run: ./build.sh
        - name: run
          run: podman run hello
