---
name: build
on: [ push ]
jobs:
  make:
    name: run make
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: make
          run: make -C $GITHUB_WORKSPACE
        - name: run
          run: $GITHUB_WORKSPACE/hello
