---
name: build
on: [ push ]
jobs:
  make-native:
    name: make native
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: make
          run: make
        - name: run
          run: ./hello
        - name: build container
          run: |
              c=$(buildah from gcr.io/distroless/static-debian10)
              buildah add --chmod 555 $c hello /bin/
              buildah config --author 'William Good' --cmd /bin/hello $c
              buildah commit $c hello
        - name: run container
          run: podman run --rm hello
  make-container-gcc:
    name: make container (gcc)
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: build
          run: ./build.sh
        - name: run
          run: podman run hello
  make-container-ubuntu:
    name: make container (ubuntu)
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: build
          run: ./build-ubuntu.sh
        - name: run
          run: podman run hello
