---
name: build
on: [ push ]
jobs:
  make-native:
    name: make native
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: make
          run: make
        - name: run
          run: ./hello
        - name: registry login
          uses: redhat-actions/podman-login@v1
          with:
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
              registry: ghcr.io
        - name: sync deps
          run: skopeo sync --src docker --dest docker --scoped gcr.io/distroless/static-debian11:latest ghcr.io/${{ github.actor }}
        - name: build container
          run: |
              c=$(buildah from gcr.io/distroless/static-debian10)
              buildah add --chmod 555 $c hello /bin/
              buildah config --author 'William Good' --cmd /bin/hello $c
              buildah commit $c hello
        - name: run container
          run: podman run --rm hello
        - name: push to registry
          id: push-to-registry
          uses: redhat-actions/push-to-registry@v2
          with:
              image: hello
              tags: latest
              registry: ghcr.io/${{ github.actor }}
        - name: show push results
          run: echo "image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"[

  make-container-gcc:
    name: make container (gcc)
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: build
          run: ./build.sh
        - name: run
          run: podman run hello
  make-container-ubuntu:
    name: make container (ubuntu)
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: build
          run: ./build-ubuntu.sh
        - name: run
          run: podman run hello
