---
name: build
on: [ push ]
jobs:
  make:
    name: run make
    runs-on: ubuntu-latest
    steps:
        - name: pull
          uses: actions/checkout@v2
        - name: make
          working-directory: ${{ env.GITHUB_WORKSPACE }}
          run: make
        - name: run
          run: $GITHUB_WORKSPACE/hello
